

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      default-zone: http://localhost:8761/eureka

  server:
    enableSelfPreservation: false

spring:
  application:
    name: EUREKA-NAMING-SERVER